### ISSUE TITLE
Set up Scanner release branch without the Parser stuff

### ISSUE THREAD

**Issue by ehx-v1** [SysprogV2/SysProg2015#6]
Basically just a new branch where the following parts are changed:

- Parser.cpp, Parser.h, ParseTree.cpp, ParseTree.h removed
- other files only used by Parser also removed to save executable size
- makefiles updated to build the Scanner
- `else`, `int`, `read` and `write` removed from keyword list
- main() for Scanner created if it doesn't exist yet

**Comment by yutamago** [comment]
This issue was moved to SysprogV2/Sysprog2017#2
